import type { AdBanner, FeedId, LocalEvent, Restaurant, Venue } from "./types";

export const FEED_REVISION = 5;
export const FEED_LAST_SYNCED = "2026-09-05T21:00:00+08:00";
export const FEED_REFRESH_HOURS = 4;

export const DAYDREAM_REFERRAL_URL = "https://daydreamprohk.ai";
export const DAYDREAM_BRAND = "Daydream Pro 香港命理大師";
export const DAYDREAM_TAGLINE = "睇完活動，問吓 AI 大師今日嘅愛情・事業・偏財運 🍀";

export const FEEDS: {
  id: FeedId;
  name: string;
  blurb: string;
  sporttimeNote?: string;
}[] = [
  {
    id: "global-sports",
    name: "國際賽事",
    blurb: "英超、NBA、F1 賽程自動入曆，開波前後接酒吧枱位。",
    sporttimeNote: "賽程核心",
  },
  {
    id: "hk-sports",
    name: "港超／本地賽",
    blurb: "傑志、東方、香港隊、啟德體育園賽事。",
  },
  {
    id: "concerts",
    name: "演唱會",
    blurb: "紅館、亞博、啟德：演出當日入曆，散場接訂座。",
  },
  {
    id: "ticket-drops",
    name: "搶飛日子",
    blurb: "公開發售／會員預購倒數，開售前清出空白檔。",
  },
  {
    id: "malls",
    name: "商場限時",
    blurb: "海港城、K11、ifc、時代廣場會員夜與折扣窗。",
  },
  {
    id: "arts",
    name: "演藝展覽",
    blurb: "西九、M+、會展、戲曲中心檔期。",
  },
  {
    id: "movies",
    name: "電影首映",
    blurb: "iSquare、圓方、MCL 優先場／午夜場，散場接宵夜。",
  },
  {
    id: "festivals",
    name: "節慶嘉年華",
    blurb: "美酒佳餚、中環海濱、西九大節日，入曆即配餐飲。",
  },
  {
    id: "workshops",
    name: "工作坊",
    blurb: "PMQ、K11 Art House 烹飪・陶藝・手作，預前配輕食。",
  },
  {
    id: "nightlife",
    name: "蒲點酒吧",
    blurb: "蘭桂坊、Soho、尖東 DJ Set，尾班車前即睇通宵點心。",
  },
];

export const VENUES: Venue[] = [
  {
    id: "coliseum",
    name: "紅磡香港體育館",
    district: "紅磡",
    address: "香港九龍紅磡暢運道 9 號",
    lat: 22.3014,
    lng: 114.182,
    mtr: "紅磡站",
    lastTrain: "00:32",
    commuteFromCentralMin: 18,
    tags: ["演唱會", "紅館"],
  },
  {
    id: "asiaworld",
    name: "亞洲國際博覽館",
    district: "赤鱲角",
    address: "香港大嶼山香港國際機場",
    lat: 22.3215,
    lng: 113.942,
    mtr: "機場／東涌站",
    lastTrain: "00:48",
    commuteFromCentralMin: 42,
    tags: ["演唱會", "亞博"],
  },
  {
    id: "kai-tak",
    name: "啟德體育園",
    district: "啟德",
    address: "九龍啟德承啟道",
    lat: 22.324,
    lng: 114.2,
    mtr: "啟德站",
    lastTrain: "00:28",
    commuteFromCentralMin: 24,
    tags: ["體育", "啟德"],
  },
  {
    id: "mk-stadium",
    name: "旺角大球場",
    district: "旺角",
    address: "九龍何文田花墟道 37 號",
    lat: 22.3186,
    lng: 114.1735,
    mtr: "旺角站／旺角東站",
    lastTrain: "00:35",
    commuteFromCentralMin: 16,
    tags: ["港超", "足球"],
  },
  {
    id: "harbour-city",
    name: "海港城",
    district: "尖沙咀",
    address: "九龍尖沙咀廣東道 3-27 號",
    lat: 22.2959,
    lng: 114.168,
    mtr: "尖沙咀站／柯士甸站",
    lastTrain: "00:42",
    commuteFromCentralMin: 12,
    tags: ["商場", "尖沙咀"],
  },
  {
    id: "k11",
    name: "K11 MUSEA",
    district: "尖沙咀",
    address: "九龍尖沙咀梳士巴利道 18 號",
    lat: 22.294,
    lng: 114.174,
    mtr: "尖東站",
    lastTrain: "00:40",
    commuteFromCentralMin: 14,
    tags: ["商場", "K11", "Art House"],
  },
  {
    id: "ifc",
    name: "ifc mall",
    district: "中環",
    address: "香港中環金融街 8 號",
    lat: 22.2855,
    lng: 114.158,
    mtr: "香港站／中環站",
    lastTrain: "00:50",
    commuteFromCentralMin: 6,
    tags: ["商場", "中環"],
  },
  {
    id: "times-square",
    name: "時代廣場",
    district: "銅鑼灣",
    address: "香港銅鑼灣勿地臣街 1 號",
    lat: 22.2783,
    lng: 114.182,
    mtr: "銅鑼灣站",
    lastTrain: "00:46",
    commuteFromCentralMin: 12,
    tags: ["商場", "銅鑼灣"],
  },
  {
    id: "mplus",
    name: "M+",
    district: "西九",
    address: "西九文化區博物館道 38 號",
    lat: 22.3016,
    lng: 114.157,
    mtr: "柯士甸站／九龍站",
    lastTrain: "00:38",
    commuteFromCentralMin: 14,
    tags: ["展覽", "西九"],
  },
  {
    id: "xiqu",
    name: "戲曲中心",
    district: "西九",
    address: "西九文化區博物館道 8 號",
    lat: 22.301,
    lng: 114.156,
    mtr: "柯士甸站",
    lastTrain: "00:38",
    commuteFromCentralMin: 14,
    tags: ["戲曲", "西九"],
  },
  {
    id: "hkcec",
    name: "香港會議展覽中心",
    district: "灣仔",
    address: "香港灣仔博覽道 1 號",
    lat: 22.2807,
    lng: 114.173,
    mtr: "灣仔站／會展站",
    lastTrain: "00:44",
    commuteFromCentralMin: 8,
    tags: ["會展", "展覽"],
  },
  {
    id: "home",
    name: "家中／酒吧觀賽",
    district: "全港",
    address: "按你日曆地點",
    lat: 22.3,
    lng: 114.17,
    mtr: "就近車站",
    lastTrain: "00:40",
    commuteFromCentralMin: 0,
    tags: ["直播", "體育"],
  },
  {
    id: "isquare",
    name: "iSquare 英皇戲院",
    district: "尖沙咀",
    address: "尖沙咀彌敦道 63 號 iSquare",
    lat: 22.2983,
    lng: 114.173,
    mtr: "尖沙咀站",
    lastTrain: "00:42",
    commuteFromCentralMin: 13,
    tags: ["戲院", "電影", "尖沙咀"],
  },
  {
    id: "elements",
    name: "圓方 PREMIERE ELEMENTS",
    district: "西九龍",
    address: "柯士甸道西 1 號圓方",
    lat: 22.304,
    lng: 114.16,
    mtr: "九龍站／柯士甸站",
    lastTrain: "00:38",
    commuteFromCentralMin: 14,
    tags: ["戲院", "電影"],
  },
  {
    id: "hkfwp",
    name: "中環海濱活動空間",
    district: "中環",
    address: "中環龍和道 9 號",
    lat: 22.284,
    lng: 114.163,
    mtr: "中環站／香港站",
    lastTrain: "00:50",
    commuteFromCentralMin: 9,
    tags: ["嘉年華", "美酒佳餚"],
  },
  {
    id: "wk-artpark",
    name: "西九文化區藝術公園",
    district: "西九",
    address: "西九文化區博物館道",
    lat: 22.303,
    lng: 114.16,
    mtr: "九龍站",
    lastTrain: "00:38",
    commuteFromCentralMin: 14,
    tags: ["嘉年華", "戶外"],
  },
  {
    id: "pmq",
    name: "PMQ 元創方",
    district: "上環",
    address: "中環鴨巴甸街 35 號",
    lat: 22.283,
    lng: 114.153,
    mtr: "上環站／中環站",
    lastTrain: "00:48",
    commuteFromCentralMin: 8,
    tags: ["工作坊", "手作"],
  },
  {
    id: "k11-arthouse",
    name: "K11 Art House",
    district: "尖沙咀",
    address: "K11 MUSEA L2",
    lat: 22.294,
    lng: 114.174,
    mtr: "尖東站",
    lastTrain: "00:40",
    commuteFromCentralMin: 14,
    tags: ["工作坊", "Art House"],
  },
  {
    id: "lkf",
    name: "蘭桂坊",
    district: "中環",
    address: "中環蘭桂坊",
    lat: 22.2806,
    lng: 114.155,
    mtr: "中環站 D2",
    lastTrain: "00:48",
    commuteFromCentralMin: 5,
    tags: ["酒吧", "蒲點", "蘭桂坊"],
  },
  {
    id: "soho",
    name: "蘇豪 Soho",
    district: "中環",
    address: "中環蘇豪 Staunton St",
    lat: 22.282,
    lng: 114.153,
    mtr: "中環站",
    lastTrain: "00:48",
    commuteFromCentralMin: 7,
    tags: ["酒吧", "餐酒館"],
  },
];

export const EVENTS: LocalEvent[] = [
  {
    id: "eason-fear",
    title: "陳奕迅 FEAR AND DREAMS",
    titleEn: "Eason Chan Fear and Dreams",
    category: "concert",
    feedId: "concerts",
    venueId: "coliseum",
    startAt: "2026-09-12T20:00:00+08:00",
    endAt: "2026-09-12T22:30:00+08:00",
    ticketDropAt: "2026-09-01T10:00:00+08:00",
    relatedEventId: "eason-drop",
    description:
      "紅館壓軸場。散場約 22:30，黃埔／紅磡一帶宵夜需求極高。建議預先鎖定步行 10 分鐘內的枱位，並預留趕紅磡站尾班車的時間。",
    tags: ["紅館", "陳奕迅", "演唱會", "Eason"],
    mood: "熱血・派對",
  },
  {
    id: "eason-drop",
    title: "搶飛：陳奕迅紅館加場公開發售",
    titleEn: "Eason Chan ticket drop",
    category: "ticket-drop",
    feedId: "ticket-drops",
    venueId: "coliseum",
    startAt: "2026-09-01T10:00:00+08:00",
    endAt: "2026-09-01T10:30:00+08:00",
    relatedEventId: "eason-fear",
    description: "Cityline 開售。開售前一晚會清出 09:45–10:30 空白檔，並提前提醒網絡備援。",
    tags: ["搶飛", "Cityline", "陳奕迅"],
    ticketType: "public",
  },
  {
    id: "jacky-60",
    title: "張學友 60+ 巡迴演唱會香港站",
    titleEn: "Jacky Cheung 60+",
    category: "concert",
    feedId: "concerts",
    venueId: "asiaworld",
    startAt: "2026-10-03T20:00:00+08:00",
    endAt: "2026-10-03T22:45:00+08:00",
    relatedEventId: "jacky-drop",
    description: "亞博場地。散場後建議預先訂東涌或市區宵夜，避免現場等位，並對準機場快線／尾班車。",
    tags: ["亞博", "張學友", "演唱會"],
    mood: "經典・回憶",
  },
  {
    id: "jacky-drop",
    title: "搶飛：張學友 60+ 會員預購",
    titleEn: "Jacky Cheung pre-sale",
    category: "ticket-drop",
    feedId: "ticket-drops",
    venueId: "asiaworld",
    startAt: "2026-09-05T10:00:00+08:00",
    endAt: "2026-09-05T11:00:00+08:00",
    relatedEventId: "jacky-60",
    description: "信用卡優先購。會把「搶飛」標成專注時段，並推送網絡備援提醒。",
    tags: ["搶飛", "優先購", "張學友"],
    ticketType: "presale",
  },
  {
    id: "kitchee-eastern",
    title: "港超：傑志 vs 東方",
    titleEn: "Kitchee vs Eastern",
    category: "sports",
    feedId: "hk-sports",
    venueId: "mk-stadium",
    startAt: "2026-09-06T20:00:00+08:00",
    endAt: "2026-09-06T22:00:00+08:00",
    description: "旺角大球場晚場。賽前旺角食肆高峰，建議 18:00 前入座；賽後可轉酒吧小食。",
    tags: ["港超", "傑志", "東方", "旺角"],
    mood: "熱血・球迷",
  },
  {
    id: "hk-team",
    title: "國際友誼賽：香港 vs 敘利亞",
    titleEn: "Hong Kong vs Syria",
    category: "sports",
    feedId: "hk-sports",
    venueId: "kai-tak",
    startAt: "2026-09-19T20:00:00+08:00",
    endAt: "2026-09-19T22:00:00+08:00",
    description: "啟德主場夜賽。啟德／九龍城一帶賽後交通擠塞，宜在園區內或步行圈預先訂座。",
    tags: ["香港隊", "啟德", "足球"],
  },
  {
    id: "arsenal-chelsea",
    title: "英超：阿仙奴 vs 車路士（香港時間）",
    titleEn: "Arsenal vs Chelsea",
    category: "sports",
    feedId: "global-sports",
    venueId: "home",
    startAt: "2026-09-13T19:30:00+08:00",
    endAt: "2026-09-13T21:30:00+08:00",
    description: "香港時間晚場。可改為酒吧觀賽，開波前鎖定高腳枱，賽後不用再搵位。",
    tags: ["英超", "阿仙奴", "車路士", "直播"],
  },
  {
    id: "nba-opening",
    title: "NBA 揭幕戰：湖人 vs 勇士（香港時間）",
    titleEn: "Lakers vs Warriors",
    category: "sports",
    feedId: "global-sports",
    venueId: "home",
    startAt: "2026-10-22T10:00:00+08:00",
    endAt: "2026-10-22T12:30:00+08:00",
    description: "清晨直播。可把「早午餐 + 觀賽」捆成一個行程，避開週末早市等位。",
    tags: ["NBA", "湖人", "勇士", "直播"],
  },
  {
    id: "harbour-night",
    title: "海港城 Fashion Week 會員夜",
    titleEn: "Harbour City member night",
    category: "mall",
    feedId: "malls",
    venueId: "harbour-city",
    startAt: "2026-09-11T18:00:00+08:00",
    endAt: "2026-09-11T22:00:00+08:00",
    description: "限時 8 折及泊車優惠。尖沙咀晚市餐廳可作為散場後承接，建議 21:00 前後入座。",
    tags: ["海港城", "限時", "購物"],
  },
  {
    id: "k11-night",
    title: "K11 MUSEA Super Night 限時推廣",
    titleEn: "K11 Super Night",
    category: "mall",
    feedId: "malls",
    venueId: "k11",
    startAt: "2026-09-18T17:00:00+08:00",
    endAt: "2026-09-18T21:30:00+08:00",
    description: "餐飲商戶滿 $400 送 $80。適合演唱會／展覽前後順路，禮券可與訂座同時用。",
    tags: ["K11", "餐飲優惠", "尖沙咀"],
  },
  {
    id: "ifc-happy",
    title: "ifc mall Happy Hour 商戶聯盟",
    titleEn: "ifc Happy Hour",
    category: "mall",
    feedId: "malls",
    venueId: "ifc",
    startAt: "2026-09-04T17:30:00+08:00",
    endAt: "2026-09-04T20:00:00+08:00",
    description: "中環放工檔。會避開你已有的會議，只推空檔內可抵達的枱位。",
    tags: ["ifc", "Happy Hour", "中環"],
  },
  {
    id: "times-beauty",
    title: "時代廣場 Beauty Week 限時",
    titleEn: "Times Square Beauty Week",
    category: "mall",
    feedId: "malls",
    venueId: "times-square",
    startAt: "2026-09-20T12:00:00+08:00",
    endAt: "2026-09-20T21:00:00+08:00",
    description: "銅鑼灣全日檔。可與晚餐訂座捆綁，把逛完直接轉化成入座。",
    tags: ["時代廣場", "Beauty", "銅鑼灣"],
  },
  {
    id: "kusama",
    title: "M+：草間彌生 — 無限的網",
    titleEn: "Yayoi Kusama at M+",
    category: "exhibition",
    feedId: "arts",
    venueId: "mplus",
    startAt: "2026-09-13T14:00:00+08:00",
    endAt: "2026-09-13T17:00:00+08:00",
    description: "西九下午場。散場後可步行至戲曲中心或柯士甸晚餐，無需過海。",
    tags: ["M+", "展覽", "西九", "草間彌生"],
    mood: "文青・打卡",
  },
  {
    id: "peony",
    title: "戲曲中心：《牡丹亭》",
    titleEn: "The Peony Pavilion",
    category: "exhibition",
    feedId: "arts",
    venueId: "xiqu",
    startAt: "2026-09-26T19:30:00+08:00",
    endAt: "2026-09-26T22:00:00+08:00",
    description: "晚場約 2.5 小時。西九晚市步行圈內可預留 22:15 後入座，並對準柯士甸站尾班車。",
    tags: ["戲曲", "西九", "牡丹亭"],
  },
  {
    id: "art-basel-week",
    title: "Art Week 會展公眾日",
    titleEn: "Art Week HKCEC",
    category: "exhibition",
    feedId: "arts",
    venueId: "hkcec",
    startAt: "2026-09-27T11:00:00+08:00",
    endAt: "2026-09-27T18:00:00+08:00",
    description: "灣仔會展。午餐／下午茶時段是黃金入座窗，建議 12:30 先鎖窗邊位。",
    tags: ["Art Week", "會展", "灣仔"],
  },
  {
    id: "dune-premiere",
    title: "《沙丘 3》香港 IMAX 午夜場首映",
    titleEn: "Dune 3 IMAX Midnight Premiere",
    category: "movie",
    feedId: "movies",
    venueId: "isquare",
    startAt: "2026-09-25T23:55:00+08:00",
    endAt: "2026-09-26T02:40:00+08:00",
    description: "iSquare IMAX 午夜場。散場後尖沙咀通宵點心選擇少，享時已為你預留紅磡／佐敦 24 小時食肆。",
    tags: ["電影", "IMAX", "沙丘", "午夜場"],
    ticketType: "public",
    mood: "科幻・約會",
  },
  {
    id: "ghibli-fest",
    title: "吉卜力動畫回顧展 優先場",
    titleEn: "Ghibli Retrospective",
    category: "movie",
    feedId: "movies",
    venueId: "elements",
    startAt: "2026-10-10T11:30:00+08:00",
    endAt: "2026-10-10T14:00:00+08:00",
    description: "圓方 PREMIERE ELEMENTS。連場長片，散場後建議步行到西九草地下午茶，或圓方高層餐廳。",
    tags: ["電影", "吉卜力", "動畫"],
    mood: "療癒・打卡",
  },
  {
    id: "wine-dine",
    title: "香港美酒佳餚巡禮 2026",
    titleEn: "HK Wine & Dine Festival",
    category: "festival",
    feedId: "festivals",
    venueId: "hkfwp",
    startAt: "2026-10-23T18:00:00+08:00",
    endAt: "2026-10-23T23:00:00+08:00",
    description: "中環海濱 4 日嘉年華。傍晚入場人流極高，預先在步行圈內訂晚餐，避免 8 點後等位。",
    tags: ["美酒佳餚", "嘉年華", "中環"],
    mood: "派對・約會",
  },
  {
    id: "freaks-out",
    title: "西九音樂節 Freaks Out",
    titleEn: "Freaks Out Music Festival",
    category: "festival",
    feedId: "festivals",
    venueId: "wk-artpark",
    startAt: "2026-11-15T14:00:00+08:00",
    endAt: "2026-11-15T22:30:00+08:00",
    description: "西九大草地戶外音樂節。散場前可在柯士甸站圈預留晚餐／酒吧枱，避開散場高峰。",
    tags: ["音樂節", "西九", "戶外"],
  },
  {
    id: "pmq-cooking",
    title: "PMQ 星級大廚烹飪班：手工意粉",
    titleEn: "PMQ Cooking Workshop",
    category: "workshop",
    feedId: "workshops",
    venueId: "pmq",
    startAt: "2026-09-20T14:00:00+08:00",
    endAt: "2026-09-20T17:00:00+08:00",
    description: "上環 PMQ 3 小時烹飪班。課前建議先到 Soho 輕食咖啡，課後可直落蘭桂坊。",
    tags: ["烹飪班", "PMQ", "手作"],
    mood: "興趣班・朋友",
  },
  {
    id: "k11-pottery",
    title: "K11 Art House 陶藝一日體驗",
    titleEn: "Pottery Experience at K11 Art House",
    category: "workshop",
    feedId: "workshops",
    venueId: "k11-arthouse",
    startAt: "2026-10-04T10:30:00+08:00",
    endAt: "2026-10-04T13:30:00+08:00",
    description: "尖沙咀 K11 Art House。課前建議預訂 K11 內早餐／Brunch，課後可接 MUSEA 晚餐。",
    tags: ["陶藝", "K11", "Art House"],
    mood: "約會・打卡",
  },
  {
    id: "lkf-dj-set",
    title: "蘭桂坊 MusicBoxx 週末 DJ Set",
    titleEn: "LKF MusicBoxx Weekend",
    category: "nightlife",
    feedId: "nightlife",
    venueId: "lkf",
    startAt: "2026-09-12T22:30:00+08:00",
    endAt: "2026-09-13T04:30:00+08:00",
    description: "蘭桂坊深夜 DJ。零晨 4 點後尾班車已過，享時為你對準通宵點心／Call 的士連結。",
    tags: ["蘭桂坊", "DJ", "酒吧"],
    mood: "派對・蒲",
  },
  {
    id: "soho-wine",
    title: "Soho 自然酒酒吧小週末",
    titleEn: "Soho Natural Wine Pop-up",
    category: "nightlife",
    feedId: "nightlife",
    venueId: "soho",
    startAt: "2026-09-19T19:30:00+08:00",
    endAt: "2026-09-19T23:30:00+08:00",
    description: "蘇豪 Staunton St 期間限定。散場前步行 5 分鐘有高質中餐廳作第二round，尾班車安全。",
    tags: ["Soho", "酒吧", "自然酒"],
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "tsui-garden",
    name: "翠園",
    cuisine: "粵菜",
    district: "黃埔",
    address: "紅磡黃埔新天地第 4 期",
    priceLevel: 3,
    nearVenueIds: ["coliseum"],
    walkMinutesByVenue: { coliseum: 8 },
    mtrStation: "黃埔站",
    lastTrainSafe: true,
    dietary: ["粵菜", "海鮮"],
    seatsLeft: 18,
    openUntil: "23:30",
    availableSlots: ["22:45", "23:00"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 48,
    autoChatReady: true,
    whatsapp: "85251230001",
    pitch: "紅館散場 8 分鐘步行，專設演唱會夜場留位。",
    ambiance: ["family", "celebration", "post-event"],
    conversionRate30d: 0.72,
    auctionBid: { eventId: "eason-fear", bidPerBooking: 58, boostedSlotStart: "2026-09-12T22:00:00+08:00", boostedSlotEnd: "2026-09-13T01:00:00+08:00" },
    adCreative: { badgeLabel: "紅館夥伴", headline: "紅館散場熱選" },
  },
  {
    id: "harbourside-izakaya",
    name: "海旁居酒屋",
    cuisine: "日本菜",
    district: "紅磡",
    address: "紅磡灣中心海旁",
    priceLevel: 2,
    nearVenueIds: ["coliseum"],
    walkMinutesByVenue: { coliseum: 10 },
    mtrStation: "紅磡站",
    lastTrainSafe: true,
    dietary: ["日本菜", "海鮮"],
    seatsLeft: 10,
    openUntil: "01:00",
    availableSlots: ["22:50", "23:15"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 36,
    autoChatReady: true,
    whatsapp: "85251230002",
    pitch: "宵夜時段仍有 4 人位，清酒套餐適合散場。",
    ambiance: ["post-event", "date"],
    conversionRate30d: 0.64,
  },
  {
    id: "tai-hing-hung-hom",
    name: "太興（紅磡站）",
    cuisine: "茶餐廳",
    district: "紅磡",
    address: "紅磡站 A 出口",
    priceLevel: 1,
    nearVenueIds: ["coliseum"],
    walkMinutesByVenue: { coliseum: 5 },
    mtrStation: "紅磡站",
    lastTrainSafe: true,
    dietary: ["茶餐廳", "快餐"],
    seatsLeft: 22,
    openUntil: "24:00",
    availableSlots: ["22:40", "23:00"],
    partySizes: [2, 3, 4],
    sponsored: false,
    advertiserCpa: 18,
    autoChatReady: true,
    whatsapp: "85251230003",
    pitch: "即叫即有，適合趕尾班車。",
    ambiance: ["casual"],
    conversionRate30d: 0.88,
  },
  {
    id: "mongkok-wing",
    name: "旺角雞翼酒吧",
    cuisine: "酒吧",
    district: "旺角",
    address: "旺角奶路臣街",
    priceLevel: 2,
    nearVenueIds: ["mk-stadium"],
    walkMinutesByVenue: { "mk-stadium": 7 },
    mtrStation: "旺角站",
    lastTrainSafe: true,
    dietary: ["酒吧", "小食"],
    seatsLeft: 16,
    openUntil: "02:00",
    availableSlots: ["18:00", "18:30", "22:15"],
    partySizes: [2, 4, 8],
    sponsored: true,
    advertiserCpa: 32,
    autoChatReady: true,
    whatsapp: "85251230004",
    pitch: "賽前套餐 18:00 開枱，賽後仍有高腳枱。",
    ambiance: ["post-event", "casual"],
    conversionRate30d: 0.58,
    auctionBid: { eventId: "kitchee-eastern", bidPerBooking: 42 },
    adCreative: { badgeLabel: "球迷熱選" },
  },
  {
    id: "langham-ting",
    name: "T'ang Court 唐閣",
    cuisine: "粵菜",
    district: "尖沙咀",
    address: "尖沙咀北京道",
    priceLevel: 4,
    nearVenueIds: ["harbour-city", "k11", "isquare"],
    walkMinutesByVenue: { "harbour-city": 6, k11: 9, isquare: 4 },
    mtrStation: "尖沙咀站",
    lastTrainSafe: false,
    dietary: ["粵菜", "素食可改"],
    seatsLeft: 6,
    openUntil: "22:30",
    availableSlots: ["18:30", "21:00"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 88,
    autoChatReady: true,
    whatsapp: "85251230005",
    pitch: "商場活動後 6 分鐘抵達，適合慶祝場。",
    ambiance: ["celebration", "business", "date"],
    conversionRate30d: 0.52,
  },
  {
    id: "k11-ozone",
    name: "MUSEA 海景餐酒吧",
    cuisine: "融合菜",
    district: "尖沙咀",
    address: "K11 MUSEA 高層",
    priceLevel: 3,
    nearVenueIds: ["k11", "harbour-city", "k11-arthouse"],
    walkMinutesByVenue: { k11: 2, "harbour-city": 11, "k11-arthouse": 3 },
    mtrStation: "尖東站",
    lastTrainSafe: true,
    dietary: ["融合菜", "素食可改"],
    seatsLeft: 12,
    openUntil: "00:00",
    availableSlots: ["19:00", "21:30"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 52,
    autoChatReady: true,
    whatsapp: "85251230006",
    pitch: "Super Night 消費可同時用商場禮券。",
    ambiance: ["date", "celebration", "business"],
    conversionRate30d: 0.48,
  },
  {
    id: "ifc-oyster",
    name: "中環生蠔吧",
    cuisine: "海鮮酒吧",
    district: "中環",
    address: "ifc mall 1 樓",
    priceLevel: 3,
    nearVenueIds: ["ifc", "pmq", "soho"],
    walkMinutesByVenue: { ifc: 3, pmq: 12, soho: 9 },
    mtrStation: "香港站",
    lastTrainSafe: true,
    dietary: ["海鮮", "酒吧"],
    seatsLeft: 8,
    openUntil: "23:00",
    availableSlots: ["18:00", "18:45"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 45,
    autoChatReady: true,
    whatsapp: "85251230007",
    pitch: "Happy Hour 生蠔時段，對接放工空檔。",
    ambiance: ["business", "date", "post-event"],
    conversionRate30d: 0.6,
  },
  {
    id: "wk-noodle",
    name: "西九麵家",
    cuisine: "麵食",
    district: "西九",
    address: "西九文化區藝術公園",
    priceLevel: 2,
    nearVenueIds: ["mplus", "xiqu", "elements", "wk-artpark"],
    walkMinutesByVenue: { mplus: 4, xiqu: 6, elements: 10, "wk-artpark": 3 },
    mtrStation: "柯士甸站",
    lastTrainSafe: true,
    dietary: ["麵食", "素食"],
    seatsLeft: 14,
    openUntil: "22:30",
    availableSlots: ["17:30", "21:00", "22:15"],
    partySizes: [2, 4],
    sponsored: false,
    advertiserCpa: 22,
    autoChatReady: true,
    whatsapp: "85251230008",
    pitch: "展覽散場步行 4 分鐘，無需過海。",
    ambiance: ["casual", "post-event"],
    conversionRate30d: 0.76,
  },
  {
    id: "wk-grill",
    name: "柯士甸燒",
    cuisine: "燒肉",
    district: "柯士甸",
    address: "柯士甸站鄰近",
    priceLevel: 3,
    nearVenueIds: ["mplus", "xiqu"],
    walkMinutesByVenue: { mplus: 12, xiqu: 10 },
    mtrStation: "柯士甸站",
    lastTrainSafe: true,
    dietary: ["燒肉"],
    seatsLeft: 10,
    openUntil: "23:00",
    availableSlots: ["17:45", "21:15"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 58,
    autoChatReady: true,
    whatsapp: "85251230009",
    pitch: "戲曲散場專屬 21:15 留位，步行約 10 分鐘。",
    ambiance: ["post-event", "celebration", "casual"],
    conversionRate30d: 0.5,
  },
  {
    id: "wanchai-bistro",
    name: "灣仔小酒館",
    cuisine: "西式 bistro",
    district: "灣仔",
    address: "灣仔港灣道",
    priceLevel: 2,
    nearVenueIds: ["hkcec"],
    walkMinutesByVenue: { hkcec: 6 },
    mtrStation: "會展站",
    lastTrainSafe: true,
    dietary: ["西餐", "素食可改"],
    seatsLeft: 9,
    openUntil: "23:30",
    availableSlots: ["12:30", "18:30"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 40,
    autoChatReady: true,
    whatsapp: "85251230010",
    pitch: "Art Week 午餐時段仍有窗邊位。",
    ambiance: ["business", "date"],
    conversionRate30d: 0.66,
  },
  {
    id: "kai-tak-hotpot",
    name: "啟德火鍋夜",
    cuisine: "火鍋",
    district: "啟德",
    address: "啟德體育園商舖",
    priceLevel: 2,
    nearVenueIds: ["kai-tak"],
    walkMinutesByVenue: { "kai-tak": 3 },
    mtrStation: "啟德站",
    lastTrainSafe: true,
    dietary: ["火鍋", "海鮮"],
    seatsLeft: 20,
    openUntil: "01:00",
    availableSlots: ["18:00", "22:15"],
    partySizes: [4, 6, 8],
    sponsored: true,
    advertiserCpa: 34,
    autoChatReady: true,
    whatsapp: "85251230011",
    pitch: "主場賽後不用離開園區即可入座。",
    ambiance: ["post-event", "family"],
    conversionRate30d: 0.7,
  },
  {
    id: "tung-chung-noodle",
    name: "東涌機場麵",
    cuisine: "麵食",
    district: "東涌",
    address: "東涌市中心",
    priceLevel: 1,
    nearVenueIds: ["asiaworld"],
    walkMinutesByVenue: { asiaworld: 14 },
    mtrStation: "東涌站",
    lastTrainSafe: true,
    dietary: ["麵食", "快餐"],
    seatsLeft: 16,
    openUntil: "23:30",
    availableSlots: ["22:50"],
    partySizes: [2, 4],
    sponsored: false,
    advertiserCpa: 16,
    autoChatReady: true,
    whatsapp: "85251230012",
    pitch: "亞博散場搭機場快線前的快速一餐。",
    ambiance: ["casual"],
    conversionRate30d: 0.82,
  },
  {
    id: "causeway-omakase",
    name: "銅鑼灣 Omakase",
    cuisine: "日本菜",
    district: "銅鑼灣",
    address: "銅鑼灣羅素街",
    priceLevel: 4,
    nearVenueIds: ["times-square"],
    walkMinutesByVenue: { "times-square": 5 },
    mtrStation: "銅鑼灣站",
    lastTrainSafe: false,
    dietary: ["日本菜", "海鮮"],
    seatsLeft: 2,
    openUntil: "22:00",
    availableSlots: ["18:00", "20:30"],
    partySizes: [2],
    sponsored: true,
    advertiserCpa: 96,
    autoChatReady: true,
    whatsapp: "85251230013",
    pitch: "Beauty Week 後兩人慶祝檔，只餘少量席位。",
    ambiance: ["date", "celebration"],
    conversionRate30d: 0.44,
  },
  {
    id: "sports-bar-central",
    name: "中環英超酒吧",
    cuisine: "酒吧",
    district: "中環",
    address: "蘭桂坊",
    priceLevel: 2,
    nearVenueIds: ["home", "ifc", "lkf", "soho"],
    walkMinutesByVenue: { home: 8, ifc: 9, lkf: 3, soho: 6 },
    mtrStation: "中環站",
    lastTrainSafe: true,
    dietary: ["酒吧", "小食"],
    seatsLeft: 14,
    openUntil: "02:00",
    availableSlots: ["19:00", "19:30"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 28,
    autoChatReady: true,
    whatsapp: "85251230014",
    pitch: "大屏幕直播英超，開波前鎖定高腳枱。",
    ambiance: ["post-event", "casual"],
    conversionRate30d: 0.54,
    auctionBid: { eventId: "arsenal-chelsea", bidPerBooking: 36 },
  },
  {
    id: "isquare-latenight-dim",
    name: "尖沙咀通宵點心專門店",
    cuisine: "點心",
    district: "尖沙咀",
    address: "尖沙咀金馬倫道",
    priceLevel: 2,
    nearVenueIds: ["isquare", "k11"],
    walkMinutesByVenue: { isquare: 6, k11: 11 },
    mtrStation: "尖沙咀站",
    lastTrainSafe: false,
    dietary: ["點心", "中式"],
    seatsLeft: 32,
    openUntil: "05:00",
    availableSlots: ["02:50", "03:15"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 30,
    autoChatReady: true,
    whatsapp: "85251230015",
    pitch: "iSquare 午夜場散場首選，24 小時供應燒賣點心。",
    ambiance: ["post-event", "casual"],
    conversionRate30d: 0.68,
    auctionBid: { eventId: "dune-premiere", bidPerBooking: 46 },
    adCreative: { badgeLabel: "午夜場首選", headline: "散場仲有位" },
  },
  {
    id: "elements-brunch",
    name: "圓方高層英式 Brunch",
    cuisine: "西式 brunch",
    district: "西九龍",
    address: "圓方 Elements 頂層",
    priceLevel: 3,
    nearVenueIds: ["elements", "mplus"],
    walkMinutesByVenue: { elements: 4, mplus: 11 },
    mtrStation: "九龍站",
    lastTrainSafe: true,
    dietary: ["西餐", "素食可改"],
    seatsLeft: 8,
    openUntil: "22:00",
    availableSlots: ["14:20", "14:45"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 44,
    autoChatReady: true,
    whatsapp: "85251230016",
    pitch: "吉卜力長片散場後，窗邊海景下午茶。",
    ambiance: ["date", "celebration"],
    conversionRate30d: 0.5,
    auctionBid: { eventId: "ghibli-fest", bidPerBooking: 38 },
  },
  {
    id: "hkfwp-seafood",
    name: "中環海旁海鮮樓",
    cuisine: "海鮮",
    district: "中環",
    address: "中環海濱龍和道",
    priceLevel: 3,
    nearVenueIds: ["hkfwp", "ifc"],
    walkMinutesByVenue: { hkfwp: 5, ifc: 9 },
    mtrStation: "香港站",
    lastTrainSafe: true,
    dietary: ["海鮮", "粵菜"],
    seatsLeft: 24,
    openUntil: "00:00",
    availableSlots: ["17:45", "22:45"],
    partySizes: [4, 6, 8],
    sponsored: true,
    advertiserCpa: 50,
    autoChatReady: true,
    whatsapp: "85251230017",
    pitch: "美酒佳餚節入場前／散場後 5 分鐘步行入座，泊車一條龍。",
    ambiance: ["celebration", "post-event", "business"],
    conversionRate30d: 0.62,
    auctionBid: { eventId: "wine-dine", bidPerBooking: 62 },
  },
  {
    id: "westkowloon-cafe",
    name: "西九大草地 Café",
    cuisine: "咖啡輕食",
    district: "西九",
    address: "西九藝術公園海旁",
    priceLevel: 2,
    nearVenueIds: ["wk-artpark", "elements", "mplus"],
    walkMinutesByVenue: { "wk-artpark": 4, elements: 10, mplus: 9 },
    mtrStation: "九龍站",
    lastTrainSafe: true,
    dietary: ["咖啡", "輕食", "素食可改"],
    seatsLeft: 18,
    openUntil: "22:00",
    availableSlots: ["22:45"],
    partySizes: [2, 4],
    sponsored: false,
    advertiserCpa: 24,
    autoChatReady: true,
    whatsapp: "85251230018",
    pitch: "Freaks Out 音樂節尾段先鎖枱，22:45 直落。",
    ambiance: ["date", "casual", "post-event"],
    conversionRate30d: 0.7,
  },
  {
    id: "soho-cafe",
    name: "Soho 手沖咖啡輕食",
    cuisine: "咖啡輕食",
    district: "中環",
    address: "Soho 卑利街",
    priceLevel: 2,
    nearVenueIds: ["pmq", "soho", "lkf"],
    walkMinutesByVenue: { pmq: 5, soho: 2, lkf: 6 },
    mtrStation: "中環站",
    lastTrainSafe: true,
    dietary: ["咖啡", "輕食", "素食可改"],
    seatsLeft: 10,
    openUntil: "22:00",
    availableSlots: ["13:40"],
    partySizes: [2],
    sponsored: true,
    advertiserCpa: 28,
    autoChatReady: true,
    whatsapp: "85251230019",
    pitch: "PMQ 烹飪班課前輕食，1 分鐘步行。",
    ambiance: ["casual", "date", "business"],
    conversionRate30d: 0.74,
    auctionBid: { eventId: "pmq-cooking", bidPerBooking: 32 },
  },
  {
    id: "k11-breakfast",
    name: "K11 Artisan Lounge",
    cuisine: "西式早餐",
    district: "尖沙咀",
    address: "K11 MUSEA L1",
    priceLevel: 3,
    nearVenueIds: ["k11-arthouse", "k11"],
    walkMinutesByVenue: { "k11-arthouse": 3, k11: 2 },
    mtrStation: "尖東站",
    lastTrainSafe: true,
    dietary: ["西餐", "素食可改"],
    seatsLeft: 6,
    openUntil: "22:00",
    availableSlots: ["10:00"],
    partySizes: [2],
    sponsored: true,
    advertiserCpa: 38,
    autoChatReady: true,
    whatsapp: "85251230020",
    pitch: "陶藝體驗前 10 點早餐，海景長枱打卡一流。",
    ambiance: ["date", "celebration"],
    conversionRate30d: 0.56,
    auctionBid: { eventId: "k11-pottery", bidPerBooking: 40 },
  },
  {
    id: "lkf-afterbar",
    name: "蘭桂芳宵夜車仔麵",
    cuisine: "車仔麵",
    district: "中環",
    address: "蘭桂坊德己立街",
    priceLevel: 1,
    nearVenueIds: ["lkf", "soho"],
    walkMinutesByVenue: { lkf: 2, soho: 5 },
    mtrStation: "中環站",
    lastTrainSafe: false,
    dietary: ["車仔麵", "快餐"],
    seatsLeft: 20,
    openUntil: "06:00",
    availableSlots: ["04:45"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 18,
    autoChatReady: true,
    whatsapp: "85251230021",
    pitch: "MusicBoxx 散場宵夜直落，通宵營運。",
    ambiance: ["casual", "post-event"],
    conversionRate30d: 0.8,
    auctionBid: { eventId: "lkf-dj-set", bidPerBooking: 28 },
    adCreative: { badgeLabel: "蘭桂芳直落" },
  },
  {
    id: "soho-second",
    name: "Soho 中菜二館",
    cuisine: "中式私房菜",
    district: "中環",
    address: "Soho 士丹頓街",
    priceLevel: 3,
    nearVenueIds: ["soho", "lkf"],
    walkMinutesByVenue: { soho: 3, lkf: 8 },
    mtrStation: "中環站",
    lastTrainSafe: true,
    dietary: ["粵菜", "私房菜"],
    seatsLeft: 8,
    openUntil: "23:30",
    availableSlots: ["23:20"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 48,
    autoChatReady: true,
    whatsapp: "85251230022",
    pitch: "自然酒 pop-up 後第二 round，步行 3 分鐘。",
    ambiance: ["celebration", "business"],
    conversionRate30d: 0.66,
    auctionBid: { eventId: "soho-wine", bidPerBooking: 52 },
  },
];

export const AD_BANNERS: AdBanner[] = [
  {
    id: "ad-daydream-live-header",
    slot: "live-header",
    type: "daydream-referral",
    title: "順便睇今日運勢",
    body: "享時夥伴推薦：Daydream Pro 香港命理。",
    cta: "去睇睇 →",
    url: DAYDREAM_REFERRAL_URL,
    emoji: "🍀",
    frequencyCapPerDay: 3,
  },
  {
    id: "ad-daydream-restaurant-after",
    slot: "after-restaurant",
    type: "daydream-referral",
    title: "問吓今日運程",
    body: "享時夥伴：Daydream Pro 香港命理網站。",
    cta: "免費睇 →",
    url: DAYDREAM_REFERRAL_URL,
    emoji: "🔮",
    frequencyCapPerDay: 5,
  },
  {
    id: "ad-daydream-booking-confirm",
    slot: "booking-confirm",
    type: "daydream-referral",
    title: "順便睇吓今日宜忌",
    body: "享時夥伴：Daydream Pro 香港命理網站。",
    cta: "睇睇 →",
    url: DAYDREAM_REFERRAL_URL,
    emoji: "🧧",
  },
];

export function venueById(id: string) {
  return VENUES.find((v) => v.id === id);
}

export function eventById(id: string) {
  return EVENTS.find((e) => e.id === id);
}

export function restaurantById(id: string) {
  return RESTAURANTS.find((r) => r.id === id);
}

export function eventsForFeeds(feedIds: FeedId[]) {
  return EVENTS.filter((e) => feedIds.includes(e.feedId)).sort(
    (a, b) => +new Date(a.startAt) - +new Date(b.startAt),
  );
}

export function relatedEvent(event: LocalEvent) {
  if (!event.relatedEventId) return undefined;
  return eventById(event.relatedEventId);
}

export function bannersForSlot(slot: AdBanner["slot"]) {
  return AD_BANNERS.filter((a) => a.slot === slot);
}

function spliceAll<T>(target: T[], next: T[]) {
  target.splice(0, target.length, ...next);
}

export function getCatalog() {
  return { venues: VENUES, events: EVENTS, restaurants: RESTAURANTS, adBanners: AD_BANNERS };
}

export function applyCatalog(catalog: {
  venues?: Venue[];
  events?: LocalEvent[];
  restaurants?: Restaurant[];
  adBanners?: AdBanner[];
}) {
  if (catalog.venues?.length) spliceAll(VENUES, catalog.venues);
  if (catalog.events?.length) spliceAll(EVENTS, catalog.events);
  if (catalog.restaurants?.length) spliceAll(RESTAURANTS, catalog.restaurants);
  return getCatalog();
}
