import type { FeedId, LocalEvent, Restaurant, Venue } from "./types";

export const FEED_REVISION = 4;
export const FEED_LAST_SYNCED = "2026-08-31T19:40:00+08:00";
export const FEED_REFRESH_HOURS = 4;

export const FEEDS: {
  id: FeedId;
  name: string;
  blurb: string;
  sporttimeNote?: string;
}[] = [
  {
    id: "global-sports",
    name: "國際賽事",
    blurb: "英超、NBA、F1 賽程自動入曆，開波前後接酒吧枱位。",
    sporttimeNote: "賽程核心",
  },
  {
    id: "hk-sports",
    name: "港超／本地賽",
    blurb: "傑志、東方、香港隊、啟德體育園賽事。",
  },
  {
    id: "concerts",
    name: "演唱會",
    blurb: "紅館、亞博、啟德：演出當日入曆，散場接訂座。",
  },
  {
    id: "ticket-drops",
    name: "搶飛日子",
    blurb: "公開發售／會員預購倒數，開售前清出空白檔。",
  },
  {
    id: "malls",
    name: "商場限時",
    blurb: "海港城、K11、ifc、時代廣場會員夜與折扣窗。",
  },
  {
    id: "arts",
    name: "演藝展覽",
    blurb: "西九、M+、會展、戲曲中心檔期。",
  },
];

export const VENUES: Venue[] = [
  {
    id: "coliseum",
    name: "紅磡香港體育館",
    district: "紅磡",
    address: "香港九龍紅磡暢運道 9 號",
    lat: 22.3014,
    lng: 114.182,
    mtr: "紅磡站",
    lastTrain: "00:32",
    commuteFromCentralMin: 18,
  },
  {
    id: "asiaworld",
    name: "亞洲國際博覽館",
    district: "赤鱲角",
    address: "香港大嶼山香港國際機場",
    lat: 22.3215,
    lng: 113.942,
    mtr: "機場／東涌站",
    lastTrain: "00:48",
    commuteFromCentralMin: 42,
  },
  {
    id: "kai-tak",
    name: "啟德體育園",
    district: "啟德",
    address: "九龍啟德承啟道",
    lat: 22.324,
    lng: 114.2,
    mtr: "啟德站",
    lastTrain: "00:28",
    commuteFromCentralMin: 24,
  },
  {
    id: "mk-stadium",
    name: "旺角大球場",
    district: "旺角",
    address: "九龍何文田花墟道 37 號",
    lat: 22.3186,
    lng: 114.1735,
    mtr: "旺角站／旺角東站",
    lastTrain: "00:35",
    commuteFromCentralMin: 16,
  },
  {
    id: "harbour-city",
    name: "海港城",
    district: "尖沙咀",
    address: "九龍尖沙咀廣東道 3-27 號",
    lat: 22.2959,
    lng: 114.168,
    mtr: "尖沙咀站／柯士甸站",
    lastTrain: "00:42",
    commuteFromCentralMin: 12,
  },
  {
    id: "k11",
    name: "K11 MUSEA",
    district: "尖沙咀",
    address: "九龍尖沙咀梳士巴利道 18 號",
    lat: 22.294,
    lng: 114.174,
    mtr: "尖東站",
    lastTrain: "00:40",
    commuteFromCentralMin: 14,
  },
  {
    id: "ifc",
    name: "ifc mall",
    district: "中環",
    address: "香港中環金融街 8 號",
    lat: 22.2855,
    lng: 114.158,
    mtr: "香港站／中環站",
    lastTrain: "00:50",
    commuteFromCentralMin: 6,
  },
  {
    id: "times-square",
    name: "時代廣場",
    district: "銅鑼灣",
    address: "香港銅鑼灣勿地臣街 1 號",
    lat: 22.2783,
    lng: 114.182,
    mtr: "銅鑼灣站",
    lastTrain: "00:46",
    commuteFromCentralMin: 12,
  },
  {
    id: "mplus",
    name: "M+",
    district: "西九",
    address: "西九文化區博物館道 38 號",
    lat: 22.3016,
    lng: 114.157,
    mtr: "柯士甸站／九龍站",
    lastTrain: "00:38",
    commuteFromCentralMin: 14,
  },
  {
    id: "xiqu",
    name: "戲曲中心",
    district: "西九",
    address: "西九文化區博物館道 8 號",
    lat: 22.301,
    lng: 114.156,
    mtr: "柯士甸站",
    lastTrain: "00:38",
    commuteFromCentralMin: 14,
  },
  {
    id: "hkcec",
    name: "香港會議展覽中心",
    district: "灣仔",
    address: "香港灣仔博覽道 1 號",
    lat: 22.2807,
    lng: 114.173,
    mtr: "灣仔站／會展站",
    lastTrain: "00:44",
    commuteFromCentralMin: 8,
  },
  {
    id: "home",
    name: "家中／酒吧觀賽",
    district: "全港",
    address: "按你日曆地點",
    lat: 22.3,
    lng: 114.17,
    mtr: "就近車站",
    lastTrain: "00:40",
    commuteFromCentralMin: 0,
  },
];

export const EVENTS: LocalEvent[] = [
  {
    id: "eason-fear",
    title: "陳奕迅 FEAR AND DREAMS",
    titleEn: "Eason Chan Fear and Dreams",
    category: "concert",
    feedId: "concerts",
    venueId: "coliseum",
    startAt: "2026-09-12T20:00:00+08:00",
    endAt: "2026-09-12T22:30:00+08:00",
    ticketDropAt: "2026-09-01T10:00:00+08:00",
    relatedEventId: "eason-drop",
    description:
      "紅館壓軸場。散場約 22:30，黃埔／紅磡一帶宵夜需求極高。建議預先鎖定步行 10 分鐘內的枱位，並預留趕紅磡站尾班車的時間。",
    tags: ["紅館", "陳奕迅", "演唱會", "Eason"],
  },
  {
    id: "eason-drop",
    title: "搶飛：陳奕迅紅館加場公開發售",
    titleEn: "Eason Chan ticket drop",
    category: "ticket-drop",
    feedId: "ticket-drops",
    venueId: "coliseum",
    startAt: "2026-09-01T10:00:00+08:00",
    endAt: "2026-09-01T10:30:00+08:00",
    relatedEventId: "eason-fear",
    description: "Cityline 開售。開售前一晚會清出 09:45–10:30 空白檔，並提前提醒網絡備援。",
    tags: ["搶飛", "Cityline", "陳奕迅"],
  },
  {
    id: "jacky-60",
    title: "張學友 60+ 巡迴演唱會香港站",
    titleEn: "Jacky Cheung 60+",
    category: "concert",
    feedId: "concerts",
    venueId: "asiaworld",
    startAt: "2026-10-03T20:00:00+08:00",
    endAt: "2026-10-03T22:45:00+08:00",
    relatedEventId: "jacky-drop",
    description: "亞博場地。散場後建議預先訂東涌或市區宵夜，避免現場等位，並對準機場快線／尾班車。",
    tags: ["亞博", "張學友", "演唱會"],
  },
  {
    id: "jacky-drop",
    title: "搶飛：張學友 60+ 會員預購",
    titleEn: "Jacky Cheung pre-sale",
    category: "ticket-drop",
    feedId: "ticket-drops",
    venueId: "asiaworld",
    startAt: "2026-09-05T10:00:00+08:00",
    endAt: "2026-09-05T11:00:00+08:00",
    relatedEventId: "jacky-60",
    description: "信用卡優先購。會把「搶飛」標成專注時段，並推送網絡備援提醒。",
    tags: ["搶飛", "優先購", "張學友"],
  },
  {
    id: "kitchee-eastern",
    title: "港超：傑志 vs 東方",
    titleEn: "Kitchee vs Eastern",
    category: "sports",
    feedId: "hk-sports",
    venueId: "mk-stadium",
    startAt: "2026-09-06T20:00:00+08:00",
    endAt: "2026-09-06T22:00:00+08:00",
    description: "旺角大球場晚場。賽前旺角食肆高峰，建議 18:00 前入座；賽後可轉酒吧小食。",
    tags: ["港超", "傑志", "東方", "旺角"],
  },
  {
    id: "hk-team",
    title: "國際友誼賽：香港 vs 敘利亞",
    titleEn: "Hong Kong vs Syria",
    category: "sports",
    feedId: "hk-sports",
    venueId: "kai-tak",
    startAt: "2026-09-19T20:00:00+08:00",
    endAt: "2026-09-19T22:00:00+08:00",
    description: "啟德主場夜賽。啟德／九龍城一帶賽後交通擠塞，宜在園區內或步行圈預先訂座。",
    tags: ["香港隊", "啟德", "足球"],
  },
  {
    id: "arsenal-chelsea",
    title: "英超：阿仙奴 vs 車路士（香港時間）",
    titleEn: "Arsenal vs Chelsea",
    category: "sports",
    feedId: "global-sports",
    venueId: "home",
    startAt: "2026-09-13T19:30:00+08:00",
    endAt: "2026-09-13T21:30:00+08:00",
    description: "香港時間晚場。可改為酒吧觀賽，開波前鎖定高腳枱，賽後不用再搵位。",
    tags: ["英超", "阿仙奴", "車路士", "直播"],
  },
  {
    id: "nba-opening",
    title: "NBA 揭幕戰：湖人 vs 勇士（香港時間）",
    titleEn: "Lakers vs Warriors",
    category: "sports",
    feedId: "global-sports",
    venueId: "home",
    startAt: "2026-10-22T10:00:00+08:00",
    endAt: "2026-10-22T12:30:00+08:00",
    description: "清晨直播。可把「早午餐 + 觀賽」捆成一個行程，避開週末早市等位。",
    tags: ["NBA", "湖人", "勇士", "直播"],
  },
  {
    id: "harbour-night",
    title: "海港城 Fashion Week 會員夜",
    titleEn: "Harbour City member night",
    category: "mall",
    feedId: "malls",
    venueId: "harbour-city",
    startAt: "2026-09-11T18:00:00+08:00",
    endAt: "2026-09-11T22:00:00+08:00",
    description: "限時 8 折及泊車優惠。尖沙咀晚市餐廳可作為散場後承接，建議 21:00 前後入座。",
    tags: ["海港城", "限時", "購物"],
  },
  {
    id: "k11-night",
    title: "K11 MUSEA Super Night 限時推廣",
    titleEn: "K11 Super Night",
    category: "mall",
    feedId: "malls",
    venueId: "k11",
    startAt: "2026-09-18T17:00:00+08:00",
    endAt: "2026-09-18T21:30:00+08:00",
    description: "餐飲商戶滿 $400 送 $80。適合演唱會／展覽前後順路，禮券可與訂座同時用。",
    tags: ["K11", "餐飲優惠", "尖沙咀"],
  },
  {
    id: "ifc-happy",
    title: "ifc mall Happy Hour 商戶聯盟",
    titleEn: "ifc Happy Hour",
    category: "mall",
    feedId: "malls",
    venueId: "ifc",
    startAt: "2026-09-04T17:30:00+08:00",
    endAt: "2026-09-04T20:00:00+08:00",
    description: "中環放工檔。會避開你已有的會議，只推空檔內可抵達的枱位。",
    tags: ["ifc", "Happy Hour", "中環"],
  },
  {
    id: "times-beauty",
    title: "時代廣場 Beauty Week 限時",
    titleEn: "Times Square Beauty Week",
    category: "mall",
    feedId: "malls",
    venueId: "times-square",
    startAt: "2026-09-20T12:00:00+08:00",
    endAt: "2026-09-20T21:00:00+08:00",
    description: "銅鑼灣全日檔。可與晚餐訂座捆綁，把逛完直接轉化成入座。",
    tags: ["時代廣場", "Beauty", "銅鑼灣"],
  },
  {
    id: "kusama",
    title: "M+：草間彌生 — 無限的網",
    titleEn: "Yayoi Kusama at M+",
    category: "exhibition",
    feedId: "arts",
    venueId: "mplus",
    startAt: "2026-09-13T14:00:00+08:00",
    endAt: "2026-09-13T17:00:00+08:00",
    description: "西九下午場。散場後可步行至戲曲中心或柯士甸晚餐，無需過海。",
    tags: ["M+", "展覽", "西九", "草間彌生"],
  },
  {
    id: "peony",
    title: "戲曲中心：《牡丹亭》",
    titleEn: "The Peony Pavilion",
    category: "exhibition",
    feedId: "arts",
    venueId: "xiqu",
    startAt: "2026-09-26T19:30:00+08:00",
    endAt: "2026-09-26T22:00:00+08:00",
    description: "晚場約 2.5 小時。西九晚市步行圈內可預留 22:15 後入座，並對準柯士甸站尾班車。",
    tags: ["戲曲", "西九", "牡丹亭"],
  },
  {
    id: "art-basel-week",
    title: "Art Week 會展公眾日",
    titleEn: "Art Week HKCEC",
    category: "exhibition",
    feedId: "arts",
    venueId: "hkcec",
    startAt: "2026-09-27T11:00:00+08:00",
    endAt: "2026-09-27T18:00:00+08:00",
    description: "灣仔會展。午餐／下午茶時段是黃金入座窗，建議 12:30 先鎖窗邊位。",
    tags: ["Art Week", "會展", "灣仔"],
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "tsui-garden",
    name: "翠園",
    cuisine: "粵菜",
    district: "黃埔",
    address: "紅磡黃埔新天地第 4 期",
    priceLevel: 3,
    nearVenueIds: ["coliseum"],
    walkMinutesByVenue: { coliseum: 8 },
    mtrStation: "黃埔站",
    lastTrainSafe: true,
    dietary: ["粵菜", "海鮮"],
    seatsLeft: 18,
    openUntil: "23:30",
    availableSlots: ["22:45", "23:00"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 48,
    autoChatReady: true,
    whatsapp: "85251230001",
    pitch: "紅館散場 8 分鐘步行，專設演唱會夜場留位。",
  },
  {
    id: "harbourside-izakaya",
    name: "海旁居酒屋",
    cuisine: "日本菜",
    district: "紅磡",
    address: "紅磡灣中心海旁",
    priceLevel: 2,
    nearVenueIds: ["coliseum"],
    walkMinutesByVenue: { coliseum: 10 },
    mtrStation: "紅磡站",
    lastTrainSafe: true,
    dietary: ["日本菜", "海鮮"],
    seatsLeft: 10,
    openUntil: "01:00",
    availableSlots: ["22:50", "23:15"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 36,
    autoChatReady: true,
    whatsapp: "85251230002",
    pitch: "宵夜時段仍有 4 人位，清酒套餐適合散場。",
  },
  {
    id: "tai-hing-hung-hom",
    name: "太興（紅磡站）",
    cuisine: "茶餐廳",
    district: "紅磡",
    address: "紅磡站 A 出口",
    priceLevel: 1,
    nearVenueIds: ["coliseum"],
    walkMinutesByVenue: { coliseum: 5 },
    mtrStation: "紅磡站",
    lastTrainSafe: true,
    dietary: ["茶餐廳", "快餐"],
    seatsLeft: 22,
    openUntil: "24:00",
    availableSlots: ["22:40", "23:00"],
    partySizes: [2, 3, 4],
    sponsored: false,
    advertiserCpa: 18,
    autoChatReady: true,
    whatsapp: "85251230003",
    pitch: "即叫即有，適合趕尾班車。",
  },
  {
    id: "mongkok-wing",
    name: "旺角雞翼酒吧",
    cuisine: "酒吧",
    district: "旺角",
    address: "旺角奶路臣街",
    priceLevel: 2,
    nearVenueIds: ["mk-stadium"],
    walkMinutesByVenue: { "mk-stadium": 7 },
    mtrStation: "旺角站",
    lastTrainSafe: true,
    dietary: ["酒吧", "小食"],
    seatsLeft: 16,
    openUntil: "02:00",
    availableSlots: ["18:00", "18:30", "22:15"],
    partySizes: [2, 4, 8],
    sponsored: true,
    advertiserCpa: 32,
    autoChatReady: true,
    whatsapp: "85251230004",
    pitch: "賽前套餐 18:00 開枱，賽後仍有高腳枱。",
  },
  {
    id: "langham-ting",
    name: "T'ang Court 唐閣",
    cuisine: "粵菜",
    district: "尖沙咀",
    address: "尖沙咀北京道",
    priceLevel: 4,
    nearVenueIds: ["harbour-city", "k11"],
    walkMinutesByVenue: { "harbour-city": 6, k11: 9 },
    mtrStation: "尖沙咀站",
    lastTrainSafe: false,
    dietary: ["粵菜", "素食可改"],
    seatsLeft: 6,
    openUntil: "22:30",
    availableSlots: ["18:30", "21:00"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 88,
    autoChatReady: true,
    whatsapp: "85251230005",
    pitch: "商場活動後 6 分鐘抵達，適合慶祝場。",
  },
  {
    id: "k11-ozone",
    name: "MUSEA 海景餐酒吧",
    cuisine: "融合菜",
    district: "尖沙咀",
    address: "K11 MUSEA 高層",
    priceLevel: 3,
    nearVenueIds: ["k11", "harbour-city"],
    walkMinutesByVenue: { k11: 2, "harbour-city": 11 },
    mtrStation: "尖東站",
    lastTrainSafe: true,
    dietary: ["融合菜", "素食可改"],
    seatsLeft: 12,
    openUntil: "00:00",
    availableSlots: ["19:00", "21:30"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 52,
    autoChatReady: true,
    whatsapp: "85251230006",
    pitch: "Super Night 消費可同時用商場禮券。",
  },
  {
    id: "ifc-oyster",
    name: "中環生蠔吧",
    cuisine: "海鮮酒吧",
    district: "中環",
    address: "ifc mall 1 樓",
    priceLevel: 3,
    nearVenueIds: ["ifc"],
    walkMinutesByVenue: { ifc: 3 },
    mtrStation: "香港站",
    lastTrainSafe: true,
    dietary: ["海鮮", "酒吧"],
    seatsLeft: 8,
    openUntil: "23:00",
    availableSlots: ["18:00", "18:45"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 45,
    autoChatReady: true,
    whatsapp: "85251230007",
    pitch: "Happy Hour 生蠔時段，對接放工空檔。",
  },
  {
    id: "wk-noodle",
    name: "西九麵家",
    cuisine: "麵食",
    district: "西九",
    address: "西九文化區藝術公園",
    priceLevel: 2,
    nearVenueIds: ["mplus", "xiqu"],
    walkMinutesByVenue: { mplus: 4, xiqu: 6 },
    mtrStation: "柯士甸站",
    lastTrainSafe: true,
    dietary: ["麵食", "素食"],
    seatsLeft: 14,
    openUntil: "22:30",
    availableSlots: ["17:30", "21:00", "22:15"],
    partySizes: [2, 4],
    sponsored: false,
    advertiserCpa: 22,
    autoChatReady: true,
    whatsapp: "85251230008",
    pitch: "展覽散場步行 4 分鐘，無需過海。",
  },
  {
    id: "wk-grill",
    name: "柯士甸燒",
    cuisine: "燒肉",
    district: "柯士甸",
    address: "柯士甸站鄰近",
    priceLevel: 3,
    nearVenueIds: ["mplus", "xiqu"],
    walkMinutesByVenue: { mplus: 12, xiqu: 10 },
    mtrStation: "柯士甸站",
    lastTrainSafe: true,
    dietary: ["燒肉"],
    seatsLeft: 10,
    openUntil: "23:00",
    availableSlots: ["17:45", "21:15"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 58,
    autoChatReady: true,
    whatsapp: "85251230009",
    pitch: "戲曲散場專屬 21:15 留位，步行約 10 分鐘。",
  },
  {
    id: "wanchai-bistro",
    name: "灣仔小酒館",
    cuisine: "西式 bistro",
    district: "灣仔",
    address: "灣仔港灣道",
    priceLevel: 2,
    nearVenueIds: ["hkcec"],
    walkMinutesByVenue: { hkcec: 6 },
    mtrStation: "會展站",
    lastTrainSafe: true,
    dietary: ["西餐", "素食可改"],
    seatsLeft: 9,
    openUntil: "23:30",
    availableSlots: ["12:30", "18:30"],
    partySizes: [2, 4],
    sponsored: true,
    advertiserCpa: 40,
    autoChatReady: true,
    whatsapp: "85251230010",
    pitch: "Art Week 午餐時段仍有窗邊位。",
  },
  {
    id: "kai-tak-hotpot",
    name: "啟德火鍋夜",
    cuisine: "火鍋",
    district: "啟德",
    address: "啟德體育園商舖",
    priceLevel: 2,
    nearVenueIds: ["kai-tak"],
    walkMinutesByVenue: { "kai-tak": 3 },
    mtrStation: "啟德站",
    lastTrainSafe: true,
    dietary: ["火鍋", "海鮮"],
    seatsLeft: 20,
    openUntil: "01:00",
    availableSlots: ["18:00", "22:15"],
    partySizes: [4, 6, 8],
    sponsored: true,
    advertiserCpa: 34,
    autoChatReady: true,
    whatsapp: "85251230011",
    pitch: "主場賽後不用離開園區即可入座。",
  },
  {
    id: "tung-chung-noodle",
    name: "東涌機場麵",
    cuisine: "麵食",
    district: "東涌",
    address: "東涌市中心",
    priceLevel: 1,
    nearVenueIds: ["asiaworld"],
    walkMinutesByVenue: { asiaworld: 14 },
    mtrStation: "東涌站",
    lastTrainSafe: true,
    dietary: ["麵食", "快餐"],
    seatsLeft: 16,
    openUntil: "23:30",
    availableSlots: ["22:50"],
    partySizes: [2, 4],
    sponsored: false,
    advertiserCpa: 16,
    autoChatReady: true,
    whatsapp: "85251230012",
    pitch: "亞博散場搭機場快線前的快速一餐。",
  },
  {
    id: "causeway-omakase",
    name: "銅鑼灣 Omakase",
    cuisine: "日本菜",
    district: "銅鑼灣",
    address: "銅鑼灣羅素街",
    priceLevel: 4,
    nearVenueIds: ["times-square"],
    walkMinutesByVenue: { "times-square": 5 },
    mtrStation: "銅鑼灣站",
    lastTrainSafe: false,
    dietary: ["日本菜", "海鮮"],
    seatsLeft: 2,
    openUntil: "22:00",
    availableSlots: ["18:00", "20:30"],
    partySizes: [2],
    sponsored: true,
    advertiserCpa: 96,
    autoChatReady: true,
    whatsapp: "85251230013",
    pitch: "Beauty Week 後兩人慶祝檔，只餘少量席位。",
  },
  {
    id: "sports-bar-central",
    name: "中環英超酒吧",
    cuisine: "酒吧",
    district: "中環",
    address: "蘭桂坊",
    priceLevel: 2,
    nearVenueIds: ["home", "ifc"],
    walkMinutesByVenue: { home: 8, ifc: 9 },
    mtrStation: "中環站",
    lastTrainSafe: true,
    dietary: ["酒吧", "小食"],
    seatsLeft: 14,
    openUntil: "02:00",
    availableSlots: ["19:00", "19:30"],
    partySizes: [2, 4, 6],
    sponsored: true,
    advertiserCpa: 28,
    autoChatReady: true,
    whatsapp: "85251230014",
    pitch: "大屏幕直播英超，開波前鎖定高腳枱。",
  },
];

export function venueById(id: string) {
  return VENUES.find((v) => v.id === id);
}

export function eventById(id: string) {
  return EVENTS.find((e) => e.id === id);
}

export function restaurantById(id: string) {
  return RESTAURANTS.find((r) => r.id === id);
}

export function eventsForFeeds(feedIds: FeedId[]) {
  return EVENTS.filter((e) => feedIds.includes(e.feedId)).sort(
    (a, b) => +new Date(a.startAt) - +new Date(b.startAt),
  );
}

export function relatedEvent(event: LocalEvent) {
  if (!event.relatedEventId) return undefined;
  return eventById(event.relatedEventId);
}

function spliceAll<T>(target: T[], next: T[]) {
  target.splice(0, target.length, ...next);
}

export function getCatalog() {
  return { venues: VENUES, events: EVENTS, restaurants: RESTAURANTS };
}

export function applyCatalog(catalog: {
  venues?: Venue[];
  events?: LocalEvent[];
  restaurants?: Restaurant[];
}) {
  if (catalog.venues?.length) spliceAll(VENUES, catalog.venues);
  if (catalog.events?.length) spliceAll(EVENTS, catalog.events);
  if (catalog.restaurants?.length) spliceAll(RESTAURANTS, catalog.restaurants);
  return getCatalog();
}
